spring.application.name=student.management

spring.datasource.url=jdbc:mysql://localhost:3307/student_management
spring.datasource.username=root
spring.datasource.password=Yosi-3230
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

mybatis.configuration.map-underscore-to-camel-case=true